export const DO_PLUS = 'DO_PLUS';
export const DO_MINUS = 'DO_MINUS';
export const CALCULATE_TOTAL_PLUS = 'CALCULATE_TOTAL_PLUS';
export const CALCULATE_TOTAL_MINUS = 'CALCULATE_TOTAL_MINUS';
export const DO_PAREN_A = 'DO_PAREN_A';
export const DO_PAREN_B = 'DO_PAREN_B';
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT';
export const PIN_ELEMENT = 'PIN_ELEMENT';
export const SEARCH_ELEMENT = 'SEARCH_ELEMENT';
//
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER_FAIL = 'RECEIVE_USER_FAIL';
export const RECEIVE_USER_SUCCESS = 'RECEIVE_USER_SUCCESS';
